/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.StockDao;
import dao.TransactionDao;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDateTime;
import models.Product;
import models.Transaction;

/**
 *
 * @author silva
 */
public class MainMenu extends javax.swing.JFrame {
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveStockBtn = new javax.swing.JButton();
        LoadStockBtn = new javax.swing.JButton();
        LoadTransactionsBtn = new javax.swing.JButton();
        SaveTransactionsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SaveStockBtn.setText("Save Stock");
        SaveStockBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveStockBtnMouseClicked(evt);
            }
        });

        LoadStockBtn.setText("Load Stock");
        LoadStockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadStockBtnActionPerformed(evt);
            }
        });

        LoadTransactionsBtn.setText("Load Transactions");
        LoadTransactionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadTransactionsBtnActionPerformed(evt);
            }
        });

        SaveTransactionsBtn.setText("Save Transactions");
        SaveTransactionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveTransactionsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoadTransactionsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SaveTransactionsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LoadStockBtn)
                    .addComponent(SaveStockBtn))
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(LoadTransactionsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveTransactionsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(LoadStockBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveStockBtn)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveStockBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveStockBtnMouseClicked
        var stock = new StockDao();
        stock.addNewProduct(new Product("Lata de tinta", 53.90f, "Lata de tinta comun"));
        try{
            stock.save();
        } catch(IOException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_SaveStockBtnMouseClicked

    private void LoadStockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadStockBtnActionPerformed
        try{
            var stock = new StockDao();
            stock.load();
            System.out.println(stock.getProducts().get(stock.getProducts().size() - 1).getCode());
        } catch(FileNotFoundException ex) {
            System.out.println(ex);
        }catch(ClassNotFoundException ex){
            System.out.println(ex);
        } catch(IOException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_LoadStockBtnActionPerformed

    private void LoadTransactionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadTransactionsBtnActionPerformed
        var dao = new TransactionDao();
        try{
            dao.load();
            System.out.println(dao.getTransactions());
        } catch(FileNotFoundException ex) {
            System.out.println(ex);
        }catch(ClassNotFoundException ex){
            System.out.println(ex);
        } catch(IOException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_LoadTransactionsBtnActionPerformed

    private void SaveTransactionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveTransactionsBtnActionPerformed
        var dao = new TransactionDao();
        dao.addTransaction(new Transaction(null, 100, "a vista", LocalDateTime.now()));
        try{
            dao.save();
        } catch(IOException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_SaveTransactionsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoadStockBtn;
    private javax.swing.JButton LoadTransactionsBtn;
    private javax.swing.JButton SaveStockBtn;
    private javax.swing.JButton SaveTransactionsBtn;
    // End of variables declaration//GEN-END:variables
}
